version: '3.4'

services:

  app:
    build: .
    volumes:
      - ./:/var/www/service
    env_file:
      - .env
    networks:
      - mem

  memcached:
    image: 'bitnami/memcached:latest'
    ports:
      - "11211:11211"
    expose:
      - "11211"
    networks:
      - mem


networks:
  mem: